version: '3.8'

services:
  postgres_db:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_DB: docker-db 
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: myStrongPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - my-app-network


  pgadmin_ui:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: myStrongPassword123! 
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - my-app-network

  rabbitmq_bus:
    image: rabbitmq:4.2.0-management
    container_name: rabbitmq_bus
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local